# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

parameters:
  - name: configuration
    displayName: Configuration
    values:
    - development
    - staging
    - production
    - test
    
trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- ${{ each value in parameters.configuration }}:
  - script: echo ${{ value }}
